services:
  backend:
    build: .
    container_name: web_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 3
      timeout: 10s
      start_period: 30s
      interval: 3s
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: