"""create all table

Revision ID: b4ac3230f0db
Revises:
Create Date: 2025-09-07 11:02:34.701237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ac3230f0db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('episodes', sa.BIGINT(), nullable=False),
    sa.Column('year', sa.BIGINT(), nullable=False),
    sa.Column('genre', sa.TEXT(), nullable=False),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('photo_url', sa.TEXT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.TEXT(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('animes')
    # ### end Alembic commands ###
