"""create the table UserAnime

Revision ID: db14a4f0b913
Revises: 29d8331725b3
Create Date: 2025-09-08 07:08:13.399885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db14a4f0b913'
down_revision: Union[str, Sequence[str], None] = '29d8331725b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_anime',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('anime_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_anime')
    # ### end Alembic commands ###
