"""create all table

Revision ID: 29d8331725b3
Revises: b4ac3230f0db
Create Date: 2025-09-07 11:06:27.980248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d8331725b3'
down_revision: Union[str, Sequence[str], None] = 'b4ac3230f0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animes', 'new',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animes', 'new',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
